[package]
name = "consensus-pbft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
crate-type = ["lib"]

[dependencies]
ledger-upgrade = { path = "../ledger-upgrade", version = "0.1.0" }
