[package]
name = "crossbeam-channel-select"
version = "0.1.0"
authors = ["Michael Chesser"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.9"
syn = { version = "1.0.100", features = ["full"] }
proc-macro2 = "1.0.43"
crossbeam-channel = "0.5.6"