# This is a TOML document. Boom.
network_id = 8108773
chain_id = "2024"
chain_hub = "bbc"
ssl_enable = false
node_address = "did:gdt:0x160b54be617f4bff07bd6c994fc6dd17a69d5e4e"
node_private_key = "43f47b5387b5321a712c5960074576b114835aa8e1ce1c2e6ab070d7ffb44346"
key_version = 12356


[ssl]
chain_file = "config/node.crt"
private_key_file = "config/node.pem"
private_password = "42001df2a1f54974baa38073eae2ee53"
dhparam_file = "config/dh2048.pem"
verify_file = "config/ca.crt"

[p2p_network]
heartbeat_interval = 60
listen_addr = "0.0.0.0:19301"
target_peer_connection = 50
max_connection = 2000
connect_timeout = 5
local_addr = ""
known_peers = []
consensus_listen_addr = "0.0.0.0:19401"
consensus_known_peers = []
codec_type = "default"


[db]
db_type = "rockdb"
key_vaule_max_open_files = 1000
account_db_path = "./data/account.db"
ledger_db_path = "./data/ledger.db"
key_value_db_path = "./data/key_value.db"


[genesis_block]
genesis_account = "did:gdt:0xf6b02a2d47b84e845b7e3623355f041bcb36daf1" #priv "fc5a55e22797ed20e78b438d9e3ca873877a7b55a604dfa7531c300e743c5ef1"
validators = ["did:gdt:0x160b54be617f4bff07bd6c994fc6dd17a69d5e4e"]


[consensus]
consensus_type = "pbft"
block_max_tx_size = 1000
block_max_contract_size = 100
commit_interval = 10


[json_rpc]
address = "0.0.0.0:8081"
batch_size_limit = 20
page_size_limit = 1000
content_length_limit = 1048576
#tls_cert_path = "setting/tls/ca.crt"
#tls_key_path = "setting/tls/ca.key"


[tx_pool]
capacity = 1_000_000
capacity_per_user = 10000
default_failovers = 3
max_broadcasts_per_peer = 1
snapshot_interval_secs = 180
ack_timeout_ms = 2_000
backoff_interval_ms = 30_000
batch_size = 100000
tick_interval_ms = 50
max_concurrent_inbound_syncs = 20
system_transaction_timeout_secs = 600
system_transaction_gc_interval_ms = 60_000
broadcast_max_batch_size = 30
broadcast_transaction_interval_ms = 1000
